NAME: "bravo_only"
MODEL:
  ARCHITECTURE: "deeplabv3resnet50"
  CHANOUT: 2
DATA:
  TRAIN:
    PATH: "/home/bmcv/Data/cifar-10-pngs/traintable.csv"
  VAL:
    PATH: "/home/bmcv/Data/cifar-10-pngs/testtable.csv"
  TEST:
    PATH: "/home/bmcv/Data/cifar-10-pngs/testtable.csv"
  INFERENCE:
    PATH: ""
HP:
  BATCHSIZE: 32
  NUMEPOCH: 100